# Dependabot configuration for Little Linux Helper
# Automatically creates pull requests to update dependencies
# See: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Go modules for the GUI backend
  - package-ecosystem: "gomod"
    directory: "/gui"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
    reviewers:
      - "maschkef"
    assignees:
      - "maschkef"
    commit-message:
      prefix: "deps(go)"
      prefix-development: "deps-dev(go)"
    open-pull-requests-limit: 5

  # NPM packages for the GUI frontend
  - package-ecosystem: "npm"
    directory: "/gui/web"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
    reviewers:
      - "maschkef"
    assignees:
      - "maschkef"
    commit-message:
      prefix: "deps(npm)"
      prefix-development: "deps-dev(npm)"
    open-pull-requests-limit: 10
    groups:
      # Group minor and patch updates together to reduce PR noise
      npm-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
    # Selectively ignore major updates only for packages known to have frequent breaking changes
    ignore:
      # Testing libraries often have breaking API changes - keep stable for development workflow
      - dependency-name: "@testing-library/react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@testing-library/user-event"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@testing-library/jest-dom"
        update-types: ["version-update:semver-major"]

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
    reviewers:
      - "maschkef"
    assignees:
      - "maschkef"
    commit-message:
      prefix: "deps(actions)"
    open-pull-requests-limit: 5
