#!/bin/bash
#
# lib/lib_colors.sh
# Copyright (c) 2025 wuldorf
# SPDX-License-Identifier: MIT
#
# Color definitions for console output

# Colors for output
LH_COLOR_RESET='\e[0m'
LH_COLOR_BLACK='\e[0;30m'
LH_COLOR_RED='\e[0;31m'
LH_COLOR_GREEN='\e[0;32m'
LH_COLOR_YELLOW='\e[0;33m'
LH_COLOR_BLUE='\e[0;34m'
LH_COLOR_MAGENTA='\e[0;35m'
LH_COLOR_CYAN='\e[0;36m'
LH_COLOR_WHITE='\e[0;37m'

LH_COLOR_BOLD_BLACK='\e[1;30m'
LH_COLOR_BOLD_RED='\e[1;31m'
LH_COLOR_BOLD_GREEN='\e[1;32m'
LH_COLOR_BOLD_YELLOW='\e[1;33m'
LH_COLOR_BOLD_BLUE='\e[1;34m'
LH_COLOR_BOLD_MAGENTA='\e[1;35m'
LH_COLOR_BOLD_CYAN='\e[1;36m'
LH_COLOR_BOLD_WHITE='\e[1;37m'

# Aliases for frequently used colors
LH_COLOR_HEADER="${LH_COLOR_BOLD_CYAN}"
LH_COLOR_MENU_NUMBER="${LH_COLOR_BOLD_YELLOW}"
LH_COLOR_MENU_TEXT="${LH_COLOR_CYAN}"
LH_COLOR_PROMPT="${LH_COLOR_BOLD_GREEN}"
LH_COLOR_SUCCESS="${LH_COLOR_BOLD_GREEN}"
LH_COLOR_ERROR="${LH_COLOR_BOLD_RED}"
LH_COLOR_WARNING="${LH_COLOR_BOLD_YELLOW}"
LH_COLOR_INFO="${LH_COLOR_BOLD_BLUE}"
LH_COLOR_SEPARATOR="${LH_COLOR_BLUE}"
