name: CI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

# Security: Set minimal permissions for CI workflow
permissions:
  contents: read      # Read repository contents

jobs:
  test-go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23']
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache-dependency-path: gui/go.sum
    
    - name: Verify Go version compatibility
      working-directory: ./gui
      run: |
        echo "Testing with Go version: $(go version)"
        go mod tidy
        
    - name: Build GUI backend
      working-directory: ./gui
      run: |
        go build -v ./...
        
    - name: Test GUI backend
      working-directory: ./gui
      run: |
        # Basic smoke test - try to run with help flag
        ./little-linux-helper-gui --help || true
        
    - name: Run Go tests (if any exist)
      working-directory: ./gui
      run: |
        if ls *_test.go >/dev/null 2>&1; then
          go test -v ./...
        else
          echo "No Go tests found, skipping"
        fi
        
  test-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: gui/web/package-lock.json
    
    - name: Install dependencies
      working-directory: ./gui/web
      run: npm ci
      
    - name: Build frontend
      working-directory: ./gui/web
      run: npm run build
      
    - name: Run linting (if you have it)
      working-directory: ./gui/web
      run: |
        # Uncomment if you add linting
        # npm run lint
        echo "Linting would run here"

  test-cli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Test CLI help
      run: |
        chmod +x help_master.sh
        # Basic syntax check
        bash -n help_master.sh
        echo "CLI syntax check passed"
